text = input("enter the text")
print(text)
print(type(text))
result = text.upper()
print(result)
print(text.tittle)
print(text.coampitalize())
print(result.Lower())
print(text*2)
print("no.of characters:",len(text))
print("no.of words:"len(text.split(" "))
print("no.of ")